### ISSUE TITLE
Fix SyntaxWarning with Smach & Python  3.8+ & Humble

### ISSUE THREAD

**Issue by martincerven** [ros/executive_smach#122]
Try importing smach in python3:
```
import smach
```

```
SyntaxWarning: "is not" with a literal. Did you mean "!="?
  return {k:v for (k, v) in self.__dict__.items() if k is not "_state_transitioning_lock"}
```
It was added to [Python 3.8 and higher](https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/).
There are multiple PRs already:  
- https://github.com/ros/executive_smach/pull/119
- https://github.com/ros/executive_smach/pull/97

@130s

**Comment by 130s** [comment]
Closing as the referenced PRs are merged/closed. If the issue is still persistent, please comment, also I would appreciate if anyone review https://github.com/ros/executive_smach/pull/119#issuecomment-2394803980
