### ISSUE TITLE
change development structure to have a single "master" branch until we make breaking changes and push previous distros into maintenance branches

### ISSUE THREAD

**Issue by jbohren** [ros/executive_smach#19]

**Comment by 130s** [comment]
Right now I see the following branches:

- executive_smach-1.0
- fuerte-devel
- groovy-devel
- hydro-devel
- indigo-devel
- master

Released artifacts are on the following branches according to [release repo](https://github.com/ros-gbp/executive_smach-release/blob/e6ce00aa4984cacf3044d1975319dc50984db2c8/tracks.yaml):
- hydro on `hydro-devel`
- indigo, jade, kinetic, lunar on `indigo-devel`

To keep the changes less, I would suggest using `indigo-devel` as kind of a `master`, and once there'll be a need to split we can create a new branch (same way a lot of ROS-related repositories do).

So I'm closing this for now but please feel free for further discussions.
