### ISSUE TITLE
Jade Release

### ISSUE THREAD

**Issue by wjwwood** [ros/executive_smach#36]
Is it possible to get a jade release soonish? It's on the `desktop-full` list:

http://wiki.ros.org/jade/Planning/Maintenance

Thanks.

**Comment by wjwwood** [comment]
Bump, if you don't have time, and you're alright with it, I can release the version of Indigo into Jade for you guys.

**Comment by 130s** [comment]
+1

**Comment by 130s** [comment]
And it seems already done.
