### ISSUE TITLE
SMACH Usecase Question

### ISSUE THREAD

**Issue by haritsahm** [ros/executive_smach#75]
Hi! First if all, your State Machine is Awesome! 
I'm using it to control my robot and here is my architecture so far,

![fsm](https://user-images.githubusercontent.com/26606913/91278969-1e305b00-e7af-11ea-8eb3-efa582bad4f5.png)

As you can see, after Initializing System, it will change to Task_Monitor State that will read user input from rosservice to determine the next task. My question is, is it a good idea to listen input from user using service/msg? Can I use smach for my robot task controller based on user input and it will run until we terminate the system or is it for single task only (opendoor_fsm, go_somewhere_fsm) and I have to call it from other node? Thankyou!

**Comment by bajo** [comment]
@haritsahm this is quite similar to how I used smach a few years ago. Main difference would be that I had a combined task monitor / manager.
This would listen to certain inputs (eg. input from touch interface or speech reco, scheduled task events on ROS topics), do some simple rule-based decision making process and trigger the appropriate sub-state machine (eg. go_to_charging_station).
For us this would run for days, so no need to restart it after a task was finished.

**Comment by haritsahm** [comment]
@bajo I see, thank you. Another question, if an action state is running and there is a new task that needs to be executed immidiately, how to set that action state to stop?

**Comment by bajo** [comment]
If I remember correctly you need to first preempt the currently running ActionState, after that you can execute another one.

**Comment by haritsahm** [comment]
@bajo do you have an example of requesting a preempt of a running state from other task/state? The only available example in tutorial is using a concurrence with a monitor state

**Comment by bajo** [comment]
@haritsahm sorry, no public example to point you to. But I guess it depends how you are using the actionlib state. I think you just need to send a new goal to the running actionlib state, with a preempt request as message. See for example the tutorial at http://wiki.ros.org/smach/Tutorials/Simple%20Action%20State , especially the execute_cb of the TestServer.

**Comment by haritsahm** [comment]
@bajo I will try it later. Thank you!
